import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { zipSync, strToU8 } from 'fflate';
import { afterEach, expect, it } from 'vitest';
import { createClient, type TestClient } from './helpers.js';
let client: TestClient | null = null;
afterEach(async () => { await client?.close(); client = null; });
it('installs real clothing data, refuses unsafe references and keeps adult packs out of the disabled catalog', async () => {
  client = await createClient();
  const fixture = path.resolve(import.meta.dirname, '../../../tests/fixtures/models/makehuman/clothes/female_casualsuit01');
  const pack = Buffer.from(zipSync(Object.fromEntries(readdirSync(fixture).map(name => [name, new Uint8Array(readFileSync(path.join(fixture, name)))]))));
  const endpoint = '/api/makehuman/assets?kind=clothes&label=Test&adult=false&rightsConfirmed=true';
  const installed = await client.req('POST', endpoint, pack);
  expect(installed.status).toBe(200);
  expect(installed.json.ownerPacks).toHaveLength(1);
  expect(Object.keys(installed.json.system.files).some(path => path.endsWith('female_casualsuit01.mhclo'))).toBe(true);
  const missing = Buffer.from(zipSync({ 'female_casualsuit01.mhclo': new Uint8Array(readFileSync(path.join(fixture, 'female_casualsuit01.mhclo'))) }));
  expect((await client.req('POST', endpoint, missing)).status).toBe(400);
  const invalid = Buffer.from(zipSync({ 'broken.target': strToU8('99999 0 1 0') }));
  expect((await client.req('POST', endpoint, invalid)).status).toBe(400);
  expect((await client.req('POST', endpoint.replace('adult=false', 'adult=true'), pack)).status).toBe(403);
  await client.req('PATCH', '/api/settings', { library: { nsfw: true, adultConfirmed: true } });
  const adultPack = Buffer.from(zipSync({ 'owner.target': strToU8('100 0 0.1 0') }));
  expect((await client.req('POST', endpoint.replace('kind=clothes', 'kind=targets').replace('adult=false', 'adult=true'), adultPack)).status).toBe(200);
  await client.req('PATCH', '/api/settings', { library: { nsfw: false } });
  const hidden = await client.req('GET', '/api/makehuman');
  expect(hidden.json.ownerPacks).toHaveLength(1);
  expect(Object.keys(hidden.json.core.files).some(path => path.endsWith('owner.target'))).toBe(false);
}, 60_000);
