// Writes apps/web/public/three/basis/ktx2-worker.js: three's KTX2 transcoder worker as a plain
// file instead of the blob three builds at run time. The Basis transcoder (Emscripten embind)
// needs eval, and a blob worker inherits the page's strict CSP; a worker served as its own file
// gets its own policy (the server allows eval for this one file only, which has no page access).
// Run after updating three: node tools/avatars/ktx2-worker.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { KTX2Loader } from 'three/examples/jsm/loaders/KTX2Loader.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const dir = path.join(root, 'apps/web/public/three/basis');
const js = readFileSync(path.join(dir, 'basis_transcoder.js'), 'utf8');
const fn = KTX2Loader.BasisWorker.toString();
const body = [
  `/* Generated by tools/avatars/ktx2-worker.mjs from three ${JSON.parse(readFileSync(path.join(root, 'node_modules/three/package.json'), 'utf8')).version} (MIT) and the Basis Universal transcoder (Apache-2.0). */`,
  '/* constants */',
  'let _EngineFormat = ' + JSON.stringify(KTX2Loader.EngineFormat),
  'let _EngineType = ' + JSON.stringify(KTX2Loader.EngineType),
  'let _TranscoderFormat = ' + JSON.stringify(KTX2Loader.TranscoderFormat),
  'let _BasisFormat = ' + JSON.stringify(KTX2Loader.BasisFormat),
  '/* basis_transcoder.js */',
  js,
  '/* worker */',
  fn.substring(fn.indexOf('{') + 1, fn.lastIndexOf('}')),
].join('\n');
writeFileSync(path.join(dir, 'ktx2-worker.js'), body);
console.log('wrote', path.relative(root, path.join(dir, 'ktx2-worker.js')), body.length, 'bytes');
