/**
 * One name for each thing, everywhere: the interface, Help and the docs (docs/ux/glossary.md, which a
 * test keeps in step with this list). `was` lists older names and the words other apps use.
 */
export const GLOSSARY: Array<{ term: string; means: string; was?: string }> = [
  { term: 'Tools', means: 'The button next to the message box (Ctrl/⌘K on a computer) that finds every tool, setting, place, item and person by name.', was: 'Actions and tools, command menu, the "+" button' },
  { term: 'Pinned', means: 'The tools at the top of Tools, chosen by you (Edit pins).' },
  { term: 'Version', means: 'One of the AI\'s replies to the same turn. › makes a new version; ‹ › move between them. The story state follows the version you keep.', was: 'swipe' },
  { term: 'Rewrite this version', means: 'Replaces the version on screen with a new one, instead of adding another.', was: 'Regenerate' },
  { term: 'Continue the story', means: 'Send with an empty message box: the AI writes the next part without anything from you.', was: 'Let the story continue' },
  { term: 'Make the reply longer', means: 'The AI keeps writing the last reply.', was: 'Continue the reply, /continue' },
  { term: 'Write my next line', means: 'The AI drafts your next message in the box, for you to change and send.', was: 'Impersonate' },
  { term: 'Branch', means: 'A new chat that goes on from a message; the original stays as it was.' },
  { term: 'Hide from the AI', means: 'The message stays on screen but the AI no longer reads it.', was: 'Hide from prompt' },
  { term: 'This chat', means: 'A chat\'s own settings: title, model, mode, persona, branches, export. Tap the chat\'s title.', was: 'Chat details' },
  { term: 'Mode', means: 'How much of Everloom a chat uses: Classic chat, Story or Full RPG.', was: 'feature preset' },
  { term: 'Classic chat', means: 'A plain roleplay chat: character, persona, lorebooks. One AI call per reply, no game.' },
  { term: 'Story', means: 'Classic chat plus memory, light tracking and the stage.' },
  { term: 'Full RPG', means: 'Everything: items, money, the map, people, quests, battles.' },
  { term: 'Feature', means: 'A part of Everloom you can switch off in Settings › Features. Off means gone: no buttons, no extra AI calls.', was: 'module' },
  { term: 'Story state', means: 'Everything the game keeps track of: time, places, people, items, quests, feelings. Every change can be undone.', was: 'World inspector, game state, ops' },
  { term: 'Story changes', means: 'The list of every change the story made, each with Undo.', was: 'World inspector › Changes' },
  { term: 'Story problems', means: 'Things in the story state that look wrong (like a name that matches nobody), each with a fix.', was: 'World inspector › Health' },
  { term: 'Auto-tracking', means: 'After each reply, a small extra AI call notes what changed: items, time, places, feelings.', was: 'Tracker pass, tracker' },
  { term: 'What the AI sees', means: 'The story state (time, place, who is here, what each person knows) given to the AI with every reply.', was: 'Scene block' },
  { term: 'Everything sent to the AI', means: 'The exact text the AI read for the last reply, piece by piece, with sizes.', was: 'Prompt inspector' },
  { term: 'Read my message first', means: 'An AI call that reads your message before the reply, for where you go and how long it takes. Adds a little delay.', was: 'Pre-read' },
  { term: 'Off-screen life', means: 'Now and then, an AI call in the background for what people do while you are away.' },
  { term: 'Facts', means: 'Things the story has established, which the AI keeps to.', was: 'Databank' },
  { term: 'People', means: 'Everyone in a story\'s world: where they are, what they do.', was: 'NPCs' },
  { term: 'Relationships', means: 'How people feel about you, and about each other.', was: 'Social' },
  { term: 'Story cast', means: 'The character cards a chat uses.', was: 'Characters (tool)' },
  { term: 'Outfits', means: 'The clothes you own, with Wear and Take off.' },
  { term: 'Weather & mood', means: 'The weather, the time-of-day tint and particles over the story.', was: 'Atmosphere' },
  { term: 'Memory', means: 'A summary of the story so far that the AI reads every turn.' },
  { term: 'Note to the AI', means: 'A standing instruction the AI reads every reply, like "short replies".', was: "Author's note" },
  { term: 'Lorebook', means: 'Entries the AI reads when their keywords come up in the story.', was: 'World info, Lore' },
  { term: 'Persona', means: 'The character you play.' },
  { term: 'Stage view', means: 'A scene shown like a visual novel, one line at a time, with pictures.', was: 'Stage mode' },
  { term: 'Cinematic mode', means: 'Only the story on screen, nothing else. Esc leaves it.' },
  { term: 'Main model', means: 'The AI that writes the story.' },
  { term: 'Utility model', means: 'An optional cheaper AI for small jobs: tracking, summaries, the helper.' },
  { term: 'Token', means: 'The unit AI services count text in; about three quarters of a word.' },
  { term: 'Name shield', means: 'Swaps real names for stand-ins before anything leaves your server, and back when replies arrive.' },
  { term: 'Vault', means: 'Encrypts everything Everloom stores; it opens with your passphrase.' },
  { term: 'Simple and Advanced', means: 'The two views of Settings: Simple shows what most people need, Advanced shows everything.' },
  { term: 'Experimental', means: 'Test pages for building Everloom itself, hidden unless switched on in Settings › Features.' },
];
